# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f1acb684dd04d135b092889ec77a6977540cfcdd08dd1a1961204ea5f310d3b9d10cb5b373279385f4c483530bf82a0860c01ba9517f8746f956a8a95eba11

test:
  secret_key_base: 1ba1313bd59efb7ff0b5b051a8c910272786e61caa4a0550fa1417e8689b3e1fea25040ce8c61b802a96dbf6ee1552ce33ba9cfdd695ec474558d1e0885162bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
